export const REQUEST_TOKEN = 'REQUEST_TOKEN'
export const RECIEVE_TOKEN_SUCCESS = 'RECIEVE_TOKEN_SUCCESS'
export const RECIEVE_TOKEN_ERROR = 'RECIEVE_TOKEN_ERROR'
export const DELETE_TOKEN = 'DELETE_TOKEN'

export const SET_CURRENT_GROCERY_LIST = 'SET_CURRENT_GROCERY_LIST'
export const CREATE_GROCERY_LIST = 'CREATE_GROCERY_LIST'
export const REMOVE_GROCERY_LIST = 'REMOVE_GROCERY_LIST'

export const CREATE_GROCERY_ITEM = 'CREATE_GROCERY_ITEM'
export const TOGGLE_GROCERY_ITEM = 'TOGGLE_GROCERY_ITEM'
export const REMOVE_GROCERY_ITEM = 'REMOVE_GROCERY_ITEM'

export const INIT_ROUTES = 'INIT_ROUTES'
export const PUSH_ROUTE = 'PUSH_ROUTE'
export const POP_ROUTE = 'POP_ROUTE'
export const REPLACE_ROUTE = 'REPLACE_ROUTE'

export const UI_TOGGLE_DRAWER = 'UI_TOGGLE_DRAWER'

export const REQUEST_USER = 'REQUEST_USER'
export const RECIEVE_USER_SUCCESS = 'RECIEVE_USER_SUCCESS'
export const RECIEVE_USER_ERROR = 'RECIEVE_USER_ERROR'
